# -*- coding: utf-8 -*-
"""web_scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A_0vdEHQUTnuSj3HWiDM03m5xjafCDcX
"""

import requests
from bs4 import BeautifulSoup
import pprint
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('drive')

res = requests.get('https://www.naukri.com/business-analyst-jobs?k=business%20analyst')
soup = BeautifulSoup(res.content,'html.parser')
res2 = requests.get('https://www.flipkart.com/search?q=laptop')
soup2 = BeautifulSoup(res2.content, 'html.parser')
res3 = requests.get('https://www.isid.ac.in/~statmath/index.php?module=Faculty')
soup3 = BeautifulSoup(res3.content, 'html.parser')

#########################################################################################################

# ISI Delhi faculty Data Scrapping from official website

########################################################
faculties = soup3.find_all('tr', {'class':'facdetails'})
isi_info = []
for faculty in faculties:
  col = faculty.find_all('p')
  isi_info.append((col[0].getText(), col[1].getText(),col[2].getText(),col[3].getText()))  


#print(isi_info)
isi_info_array = np.asarray(isi_info)
print(len(isi_info_array))
df = pd.DataFrame(isi_info_array)
df.columns = ['Name', 'phd_university','interest', 'email']
print(df.head())
df.to_csv('isi_information.csv')
!cp isi_information.csv "drive/My Drive/"


#####################################################################################################

# Laptop Info data scrapping from flipkart website

#######################################################
product_class = soup2.find_all('div', {'class' : '_1AtVbE col-12-12'})
product_info = []
for product in product_class:
  name = product.find('div', {'class' : '_4rR01T'})
  if name:
    name = name.getText()  
  else:
    name = "No name"
  #print(name)
  price = product.find('div', {'class' : '_30jeq3 _1_WHN1'})
  if price:
    price = price.getText()
  #print(price)
  rating = product.find('div', {'class':'_3LWZlK'})
  if rating:
    rating = rating.getText()
  #print(rating)  
  product_info.append((name,price,rating))

#print(product_info)
df = pd.DataFrame(product_info)
df.columns = ['Laptop_Name', 'Price','Rating']
df = df.drop([df.index[0],df.index[1]])
print(df.head())
df.to_csv('Laptop_info.csv')
!cp Laptop_info.csv "drive/My Drive/"
