# -*- coding: utf-8 -*-
"""words count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PxtjTML0IapawwYArIg59kv2s8i-Kcvp
"""

from google.colab import files
uploaded = files.upload()

# counting total number of words
file = "word.txt"
dataw = uploaded[file].split()
len(dataw)

# counting individual number of words using counter()
import re
from collections import Counter
file = "word.txt"
file = uploaded[file].decode("utf-8").lower()

file = re.sub("[^\w ]", "", file)
words = file.split(" ")

totalwords = len(words)
Counter(words).most_common(10)

w = {}
for c in words:
    if c in w:
       w[c] +=1
    else:
      w[c] = 1


lst = [(w[c],c) for c in w]
lst.sort()
w

l = []
i = 0.001
for k, v  in w.items():
    r = v/totalwords
    if r <= i:
       l.append((v,k))
l.sort()
l.reverse()
l

import re
counts={}
stopwords=['a','an','the','in','on','is','are','am','i','he','she','you']
words=re.compile(r'\w+')
for word in words.findall(file):
    if word not in stopwords:
        counts.setdefault(word,0)
        counts[word]+=1

def word(count):
    for w,c in counts.items():
         if count==c:
             return w
print('10 topmost occurring words in the text:')
for i in range(0,10):
    m=max(list(counts.values()))
    print(word(m))
    counts[word(m)]=0